### ISSUE TITLE
When serving nuxt in a development enviroment, the webpack UI gets messed up.

### ISSUE THREAD

**Issue by Pitu** [nuxt/webpackbar#25]
* Operating System: Windows 10 1803
* Node Version: v10.8.0
* NPM Version: 6.2.0
* webpack Version: Whatever comes with nuxt@2
* webpack-serve Version: Whatever comes with nuxt@2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```bash
  $ nuxt
```

### Expected Behavior

When using the command `next` it compiles, clears the console on most cases and then it shows you the ip and port where your app is being served on.

### Actual Behavior

Lots of text gets left behind, progressbars don't even complete and it fails to show ip and port as shown on the following picture:

![](https://lolisafe.moe/WD5lpgLk.png)

### How Do We Reproduce?
Just by running the command `nuxt`.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c19">#c19</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @Pitu. Sorry for that this issue was opening for a long time. We have made several stability improvements with [v3.0.0](https://github.com/nuxt/webpackbar/releases/tag/v3.0.0) release. `3.1.2` is the latest release and you should experience much better. Would be happy hearing your feedback about latest changes :)
