### ISSUE TITLE
The Console Gets Cleared

### ISSUE THREAD

**Issue by ahmadawais** [nuxt/webpackbar#3]
I'm trying to integrate it in [create-guten-block](https://github.com/ahmadawais/create-guten-block). 

I ejected and removed all the clear console functions so that nothing gets cleared.

Then I added `webpackbar` to it.

Configured it like you said and comment the stats comment so that we get all the stats.

But it still goes away after compiling.

Check 👇

![image](http://on.ahmda.ws/qSej/c)

Help! ⚠️

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/webpackbar/issues/c3">#c3</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @ahmadawais. Thanks for your interest 😍 Actually it is an intentional default behavior to clean it up as fast at build finishes. For keeping bars we need to also add [this](https://github.com/nuxt/webpackbar/blob/master/src/index.js#L93) condition. 

I've added some new options in `1.2.1`. Please test them respectively:

- Set `clear` option to `false` (This probably will fix the issue)
- Set `showCursor` option to `true` (It may be more appreciate to not hiding cursor during build)
- Set `stream` option to `process.std error` (other plugins may causing conflicts)

**Comment by ahmadawais** [comment]
@pi0 Wow, that was quick. Thanks for the update.

By default it works now without any settings but doesn't go to 100%

```sh
npm run build
```

![image](http://on.ahmda.ws/qSgC/c)

and for the dev routine it stops at 10%

```sh
npm start
```
![image](http://on.ahmda.ws/qSST/c)

Using 

```js
new WebpackBar( {
			clear: false,
			showCursor: true,
		} ),
```

**Comment by pi0** [comment]
Wired problem. Are your committed to a branch? I then can investigate it deeper.

**Comment by dvlden** [comment]
For me, it does not work properly either... Both dev and production compilation gets stuck almost at the end, at 95% 😭
https://d.pr/i/pvxlv5

I did not set `stream: process.stdout.error` because that throws an error and I don't even know what is that for? 

I tested this just for fun, clearing the bar sounds good for me by default, so I'll stick with that and enjoy the progress bar in webpack.

**Comment by pi0** [comment]
Anyway, I'll try to investigate and resolve this issue. Nice to hear your feedback @dvlden :)

**Comment by pi0** [comment]
@ahmadawais With `1.4.0`, `clear: false` option should be correctly working:

![image](https://user-images.githubusercontent.com/5158436/38054503-69906a4c-32ec-11e8-98dc-583c7c3d60e3.png)

**Comment by pwang2** [comment]
any update on this? The clear option is not working even after setting stream and showCursor..

**Comment by qrohlf** [comment]
@pwang2 the clear option appears to have been removed in V2, in favor of the `compiledIn` option.

**Comment by pwang2** [comment]
Good to know, thanks.

**Comment by djyde** [comment]
@qrohlf but after setting `compiledIn` to `false`, my console still gets clear

**Comment by pi0** [comment]
Hi @ahmadawais and others. 

Sorry for keeping this issue open for a long time. We have made several improvements with [v3.0.0](https://github.com/nuxt/webpackbar/releases/tag/v3.0.0) (Latest is `v3.1.2`) and now, not only the clear screen is fully removed but also webpackbar can handle concurrent logs by third parties without hiding any of them. 

Would be really happy hearing your feedbacks about the latest changes and also feel free opening new issues if having inconsistencies.
