### ISSUE TITLE
falling when terminal width < 120

### ISSUE THREAD

**Issue by Airkro** [nuxt/webpackbar#35]
### Version

[v3.0.0](https://github.com/webpackbar/releases/tag/v3.0.0)

### Steps to reproduce

use in webpack 4.x

### What is expected ?

run normally

### What is actually happening?

![abc.gif](https://cmty.s3.eu-west-1.amazonaws.com/126595796/73845460-f7df-11e8-8e88-23c6470fd204.gif)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackbar/issues/c29">#c29</a>)</em></sub></div>

**Comment by saschask** [comment]
I have the same bug and I found out that the behavior depends on the console window's width. According to the respective width, webpackbar can behave as expected, behave like shown in the GIF above or behave like shown in the GIF above but with more and more instances of the bar instead of increasing space (0% > 1% > 2% and so on... every update is rendered in a new line).

**Comment by Airkro** [comment]
Any script will do the same
